config/routes.rb
Rails.application.routes.draw do

resources :posts
resources :users, only: [:new, :create]
resources :sessions, only: [:new, :create, :destroy]

# log in route
get 'login', to: 'sessions#new', as: 'login'

post 'login', to: 'sessions#create'

# log out route
get 'logout', to: 'sessions#destroy', as: 'logout'

# sign up page route
get 'signup', to: 'users#new', as: 'signup'

get 'images', to: 'posts#index', as: 'images'

get 'uploads', to: 'posts#new', as: 'uploads'

get 'viewposts', to: 'posts#show', as: 'viewposts'

# about page route
get 'home/about'

# login page route
get 'home/login'

# sign up page route
get 'home/signup'

# home page route
root 'home#index'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    has_many_attached :uploads
    has_one_attached :cover_image
    validates :title, presence:true
end

app/models/session.rb
class Session < ApplicationRecord

end

app/models/user.rb
class User < ApplicationRecord

    has_secure_password
    has_many :posts
    validates_uniqueness_of :email
    validates :first_name, :last_name, :email, :password, presence: true
    validates :email, uniqueness: { message: ->(object, data) do
        "#{data[:value]} is already taken."
    end}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    before_action :authorized
    helper_method :current_user
    helper_method :logged_in?
    
    # finds current user by session
    def current_user
        User.find_by(id: session[:user_id])
    end

    # determines if the user is logged in
    def logged_in?
        !current_user.nil?
    end

    # determines if a user can access certain pages based on log in status
    def authorized
       redirect_to login_url, alert: "Please login or sign up to use Picto Vault" unless logged_in?
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  skip_before_action :authorized, only: [:index, :about]

  def index
  end

  def about
  end
  
  def login
  end

  def signup
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authorized, only: [:index, :show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = current_user.posts
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = current_user.posts.find(params[:id])
  end

  # GET /posts/new
  def new
    @post = current_user.posts.new
  end

  # GET /posts/1/edit
  def edit
    @post = current_user.posts.find(params[:id])
  end

  # allows users to create a post based on a given set of parameters
  def create
    @post = current_user.posts.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # allows users to update any of the defined post parameters
  def update
    @post = current_user.posts.find(params[:id])
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # allows users to delete a post
  def destroy
    @post = current_user.posts.find(params[:id])
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    
    def set_post
      @post = Post.find(params[:id])
    end

    # defines all of the parameters for posts
    def post_params
      params.require(:post).permit(:title, :description, :cover_image, uploads: [])
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  skip_before_action :authorized, only: [:new, :create]

  def new
  end

  # creates new session for users through login parameters (username, password)
  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in!"
    else
      flash.now[:alert] = "Email or password is invalid"
      render "new"
    end
  end

  # allows users to end their current session
  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end

  def page_requires_login
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  skip_before_action :authorized, only: [:new, :create]

  def new
     @user = User.new
  end

  # allows a user to create a new account based on a set of parameters
  def create
      @user = User.create(params.require(:user).permit(:first_name, :last_name, :email,        
      :password))
      if @user.save
         session[:user_id] = @user.id
         redirect_to root_url, notice: "Thank you for signing up!"
      else
         render "new"
      end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
  <%= inline_svg_tag "lock.svg", class: 'lock' %>
  <%= link_to 'Picto Vault', root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
            <%= link_to "About Us", home_about_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            My Vault
          </a>
          <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDropdown">
            <%= link_to "My Albums", '/images', class: "nav-link" %>
            <%= link_to "Create a New Album", '/uploads' , class: "nav-link" %>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<header>
   <div class="container-fluid 0px center welcome">
        <div class="jumbotron jumbotron-fluid">
        <div class="container">
            </br>
            <h1 class="display-4">Welcome to Picto Vault!</h1>
            <p class="lead">Picto Vault is a secure online repository where you can store your images. </p>
        </div>
        </div>
    </div>
</header>
</br>
<div class="center">
  <h1 class="welcome">About the Creator</h1>
</div>
</br>
<div class="container info">
  <div class="row">
      <div class="col-6">
        <div class="card border-dark shadow">
          <%= image_tag("me.png", class:"card-img-top", alt:"Sophie Michaud") %>
        </div>
      </div>
      <div class="col">
        <h4>
          Hi my name is Sophie! I'm an Engineering Systems and Computing Student currently in my fourth year studying at the University of Guelph.
        </h4>
        <div>
          </br>
          <h3>
            <strong>Contact Details</strong>
          </h3>
          <h5> sophiem@uoguelph.ca </h5>
          </br>
          <%= link_to "View Resume", 'https://drive.google.com/file/d/1oOUD5YJu4lmthfYPyeyF_1qCEh-rGm7y/view?usp=sharing', class: "btn btn-dark" %>
          <div>
            </br>
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
            <a href="https://www.linkedin.com/in/sophienmichaud/" class="fa fa-linkedin"></a>
            <a href="https://github.com/sophiemichaud" class="fa fa-github"></a>
            <a href="https://twitter.com/Sophie__Michaud" class="fa fa-twitter"></a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</br>
</br>

app/views/home/index.html.erb
<body class="welcome">
</br>
    <h1 class="welcome">Welcome to Picto Vault!</h1>
    <% if current_user %>
        You are logged in as <%= current_user.email %>.
        <%= link_to "Log Out", 'logout', class: "nav-link" %>
    <% else %>
        <div class="welcome">
            <%= link_to "Log In", 'login', class: "btn btn-dark" %> or
            <%= link_to "Sign Up", 'signup', class: "btn btn-dark" %>
        </div>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@500&display=swap" rel="stylesheet">
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <title>Picto Vault</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>

    <%= render 'home/header' %>
    <div class="container">

      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
       <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>
      <%= yield %>
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
  </div>
  </br>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: "form-control" %>
  </div>
  </br>

  <div class="form-group">
    <%= form.label :uploads %>
    <%= form.file_field :uploads, multiple: true, class: "form-control" %>
  </div>
  </br>

  <div class="form-group">
    <%= form.submit class: "btn btn-dark" %>
  </div>
<% end %>

app/views/posts/edit.html.erb
</br>
<h1>Editing Post</h1>

<%= render 'form', post: @post %>
</br>
<%= link_to 'Back', posts_path, class: "btn btn-outline-dark" %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>
<div class="row align-items-start">
  <div class="col">
    <h1 class="message">My Albums</h1>
  </div>
  <div class="col-2">
    <%= link_to 'Create a New Album', new_post_path, class: "btn btn-dark" %>
  </div>
</div>
<table>
  <tbody>
    <% @posts.each do |post| %>
      <div class="settings">
        Previewing: <%= post.title %>
        <div class="info">
        Album Created on: <%= post.created_at.strftime("%m/%d/%Y %I:%M %p") %>
        </div>
        <%= link_to 'See Post', post, class: "btn btn-outline-dark" %>
        <%= link_to 'Edit Post', edit_post_path(post), class: "btn btn-outline-dark" %>
        <%= link_to 'Delete Post', post, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-dark" %>
        </br></br>
      </div>
      <div class="row align-items-start">
        <% post.uploads.first(3).each do |upload| %>
          <div class="col">
          <% if upload.variable? %>
            <%= link_to image_tag(upload.variant(resize: "400x400")), upload, class: "md-col-3" %>
            </br></br>
          <% end %>
          </div>
          </br>
        <% end %>
      </div>
    <% end %>
  </tbody>
</table>

<br>

app/views/posts/new.html.erb
</br>
<h1>New Album</h1>

<%= render 'form', post: @post %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>

<%= sanitize @post.description %>

<div>
  <% @post.uploads.each do |upload| %>
    <% if upload.variable? %>
      <%= link_to image_tag(upload.variant(resize: "400x400")), upload %>
    <% end %>
  <% end %>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="center">
    <div class="child">
      </br>
      <h1 class="message">New to Picto Vault?</h1>
      <div class="col-md-12">
        <%= form.label :first_name, for:"validationCustom02", class:"form-label" %>
        <%= form.text_field :first_name, class:"form-control", id:"validationCustom02" %>
        <div class="valid-feedback">
          Looks good!
        </div>
      </div>
      <br/>

      <div class="col-md-12">
        <%= form.label :last_name, for:"validationCustom02", class:"form-label" %>
        <%= form.text_field :last_name, class:"form-control", id:"validationCustom02" %>
        <div class="valid-feedback">
          Looks good!
        </div>
      </div>
      <br/>

      <div class="col-md-12">
        <%= form.label :email, for:"validationCustomUsername", class:"form-label"%>
        <div class="input-group has-validation">
          <%= form.text_field :email, class:"form-control", id:"validationCustomEmail" %>
        </div>
        <div class="invalid-feedback">
            Please choose a valid email.
        </div>
      </div>
      <br/>

      <div class="col-md-12">
        <%= form.label :password, for:"validationCustom02", class:"form-label" %>
        <%= form.password_field :password, class:"form-control", id:"validationCustom02" %>
        <div class="valid-feedback">
          Looks good!
        </div>
      </div>
      <br/>

      <div class="col-12">
        <%= form.submit :Register, class:"btn btn-dark", type:"submit" %>
      </div>
      <br/>

      <div>
        <%= link_to 'Back', root_path, class:"btn btn-secondary" %>
      </div>

    </div>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="message">You're officially a Picto Vault Member!</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= user.password %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path, class:"btn btn-secondary" %>

app/views/users/new.html.erb
<%= render 'form', user: @user %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>